"""nullable sensor columns, wind fields, growing area name max 25

Revision ID: 902bb2ff3b82
Revises: b5e7d0f4c1a9
Create Date: 2026-04-20 11:06:43.747310

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '902bb2ff3b82'
down_revision: Union[str, None] = 'b5e7d0f4c1a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('growing_areas', 'name',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=25),
               existing_nullable=False)
    op.add_column('sensor_readings', sa.Column('wind_speed', sa.Float(), nullable=True))
    op.add_column('sensor_readings', sa.Column('wind_direction', sa.String(length=3), nullable=True))
    op.alter_column('sensor_readings', 'temperature',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('sensor_readings', 'humidity',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sensor_readings', 'humidity',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('sensor_readings', 'temperature',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.drop_column('sensor_readings', 'wind_direction')
    op.drop_column('sensor_readings', 'wind_speed')
    op.alter_column('growing_areas', 'name',
               existing_type=sa.String(length=25),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    # ### end Alembic commands ###
