"""initial schema

Revision ID: a217e01e6086
Revises: 
Create Date: 2026-04-15 17:38:24.871883

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = 'a217e01e6086'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permissions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('owner', 'farmer', 'hired_hand', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('customers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('growing_areas',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('area_type', sa.Enum('open_field', 'dwc_greenhouse', name='growingareatype'), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('area_acres', sa.Float(), nullable=True),
    sa.Column('area_sqft', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('role_permissions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.Enum('owner', 'farmer', 'hired_hand', name='userrole'), nullable=False),
    sa.Column('permission_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role', 'permission_id')
    )
    op.create_table('crops',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('greenhouse_compatible', sa.Boolean(), nullable=False),
    sa.Column('typical_cycle_days', sa.Integer(), nullable=False),
    sa.Column('default_harvest_customer_id', sa.Uuid(), nullable=True),
    sa.Column('default_transplant_customer_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['default_harvest_customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['default_transplant_customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('crop_cycles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('growing_area_id', sa.Uuid(), nullable=False),
    sa.Column('crop_id', sa.Uuid(), nullable=True),
    sa.Column('planned_crop_id', sa.Uuid(), nullable=True),
    sa.Column('season_year', sa.Integer(), nullable=False),
    sa.Column('cycle_number', sa.Integer(), nullable=False),
    sa.Column('planted_at', sa.Date(), nullable=False),
    sa.Column('harvested_at', sa.Date(), nullable=True),
    sa.Column('yield_unit', sa.Enum('lbs', 'bushels', name='yieldunit'), nullable=False),
    sa.Column('target_yield', sa.Float(), nullable=True),
    sa.Column('actual_yield', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('active', 'harvested', 'abandoned', 'fallow', name='cropcyclestatus'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['crop_id'], ['crops.id'], ),
    sa.ForeignKeyConstraint(['growing_area_id'], ['growing_areas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['planned_crop_id'], ['crops.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('growing_area_id', 'season_year', 'cycle_number')
    )
    op.create_table('crop_rates',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('crop_id', sa.Uuid(), nullable=False),
    sa.Column('rate_per_unit', sa.Float(), nullable=False),
    sa.Column('unit', sa.Enum('lbs', 'bushels', name='yieldunit'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['crop_id'], ['crops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('historical_summaries',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('growing_area_id', sa.Uuid(), nullable=False),
    sa.Column('crop_id', sa.Uuid(), nullable=False),
    sa.Column('week_number', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('avg_temperature', sa.Float(), nullable=False),
    sa.Column('min_temperature', sa.Float(), nullable=False),
    sa.Column('max_temperature', sa.Float(), nullable=False),
    sa.Column('avg_humidity', sa.Float(), nullable=False),
    sa.Column('min_humidity', sa.Float(), nullable=False),
    sa.Column('max_humidity', sa.Float(), nullable=False),
    sa.Column('reading_count', sa.Integer(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['crop_id'], ['crops.id'], ),
    sa.ForeignKeyConstraint(['growing_area_id'], ['growing_areas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('growing_area_id', 'crop_id', 'week_number', 'year')
    )
    op.create_table('invoices',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('customer_id', sa.Uuid(), nullable=False),
    sa.Column('crop_cycle_id', sa.Uuid(), nullable=False),
    sa.Column('rate_id', sa.Uuid(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('unit', sa.Enum('lbs', 'bushels', name='yieldunit'), nullable=False),
    sa.Column('unit_price', sa.Float(), nullable=False),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'sent', 'paid', 'voided', name='invoicestatus'), nullable=False),
    sa.Column('invoice_date', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['crop_cycle_id'], ['crop_cycles.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['rate_id'], ['crop_rates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sensor_readings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('growing_area_id', sa.Uuid(), nullable=False),
    sa.Column('crop_cycle_id', sa.Uuid(), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('humidity', sa.Float(), nullable=False),
    sa.Column('reading_source', sa.Enum('noaa', 'manual', 'sensor', name='readingsource'), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('assessment_status', sa.Enum('pending', 'processing', 'normal', 'anomalous', 'error', name='assessmentstatus'), nullable=False),
    sa.Column('assessment_summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['crop_cycle_id'], ['crop_cycles.id'], ),
    sa.ForeignKeyConstraint(['growing_area_id'], ['growing_areas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sensor_readings_area_read_at', 'sensor_readings', ['growing_area_id', 'read_at'], unique=False)
    op.create_table('yield_plans',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('growing_area_id', sa.Uuid(), nullable=False),
    sa.Column('crop_cycle_id', sa.Uuid(), nullable=False),
    sa.Column('recommended_plant_quantity', sa.Float(), nullable=False),
    sa.Column('target_yield', sa.Float(), nullable=False),
    sa.Column('confidence_level', sa.Enum('low', 'medium', 'high', name='confidencelevel'), nullable=False),
    sa.Column('reasoning', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['crop_cycle_id'], ['crop_cycles.id'], ),
    sa.ForeignKeyConstraint(['growing_area_id'], ['growing_areas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alerts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('growing_area_id', sa.Uuid(), nullable=False),
    sa.Column('crop_cycle_id', sa.Uuid(), nullable=True),
    sa.Column('triggering_reading_id', sa.Uuid(), nullable=False),
    sa.Column('alert_type', sa.Enum('temperature_high', 'temperature_low', 'humidity_high', 'humidity_low', 'combined', name='alerttype'), nullable=False),
    sa.Column('status', sa.Enum('active', 'resolved', name='alertstatus'), nullable=False),
    sa.Column('consecutive_normal_count', sa.Integer(), nullable=False),
    sa.Column('last_email_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('assessment_summary', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['crop_cycle_id'], ['crop_cycles.id'], ),
    sa.ForeignKeyConstraint(['growing_area_id'], ['growing_areas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['triggering_reading_id'], ['sensor_readings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_alerts_area_status', 'alerts', ['growing_area_id', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_alerts_area_status', table_name='alerts')
    op.drop_table('alerts')
    op.drop_table('yield_plans')
    op.drop_index('ix_sensor_readings_area_read_at', table_name='sensor_readings')
    op.drop_table('sensor_readings')
    op.drop_table('invoices')
    op.drop_table('historical_summaries')
    op.drop_table('crop_rates')
    op.drop_table('crop_cycles')
    op.drop_table('crops')
    op.drop_table('role_permissions')
    op.drop_table('growing_areas')
    op.drop_table('customers')
    op.drop_table('users')
    op.drop_table('permissions')
    # ### end Alembic commands ###
