"""add growing_area_plots table and plot fk on crop_cycles

Revision ID: dc1d3a48956d
Revises: 902bb2ff3b82
Create Date: 2026-04-20 19:13:55.845721

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc1d3a48956d'
down_revision: Union[str, None] = '902bb2ff3b82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('growing_area_plots',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('growing_area_id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=25), nullable=False),
    sa.Column('plot_type', sa.Enum('dwc_row', 'dwc_box', 'trial_strip', name='plottype'), nullable=False),
    sa.Column('length_ft', sa.Float(), nullable=True),
    sa.Column('width_ft', sa.Float(), nullable=True),
    sa.Column('area_sqft', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['growing_area_id'], ['growing_areas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('crop_cycles', sa.Column('growing_area_plot_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'crop_cycles', 'growing_area_plots', ['growing_area_plot_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'crop_cycles', type_='foreignkey')
    op.drop_column('crop_cycles', 'growing_area_plot_id')
    op.drop_table('growing_area_plots')
    # ### end Alembic commands ###
